### ISSUE TITLE
Installation of v 1.0.1 not possible

### ISSUE THREAD

**Issue by baeriwiliwonka** [ioBroker/ioBroker.phantomjs#14]
In my system an installation of this adapter in v 1.0.1 is not possible.
I tested with other new adapers, they work fine.

> $ ./iobroker add phantomjs  --host raspberrypi
NPM version: 6.9.0npm install iobroker.phantomjs@1.0.1 --loglevel error --prefix "/opt/iobroker" (System call)
In file included from ../src/DeviceINQ.h:17,                 from ../src/linux/BluetoothSerialPort.cc:13:../node_modules/nan/nan.h: In function 'void Nan::AsyncQueueWorker(Nan::AsyncWorker*)':../node_modules/nan/nan.h:2298:62: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)                                                              ^
In file included from ../src/linux/BluetoothSerialPort.cc:12:../src/linux/BluetoothSerialPort.cc: At global scope:/home/iobroker/.node-gyp/10.16.0/include/node/node.h:573:43: warning: cast between incompatible function types from 'void (*)(v8::Handle<v8::Object>)' {aka 'void (*)(v8::Local<v8::Object>)'} to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]       (node::addon_register_func) (regfunc),                          \                                           ^/home/iobroker/.node-gyp/10.16.0/include/node/node.h:607:3: note: in expansion of macro 'NODE_MODULE_X'   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)   ^~~~~~~~~~~~~../src/linux/BluetoothSerialPort.cc:23:1: note: in expansion of macro 'NODE_MODULE' NODE_MODULE(BluetoothSerialPort, InitAll) ^~~~~~~~~~~
In file included from /home/iobroker/.node-gyp/10.16.0/include/node/node.h:63,                 from ../src/linux/BluetoothSerialPort.cc:12:/home/iobroker/.node-gyp/10.16.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':/home/iobroker/.node-gyp/10.16.0/include/node/node_object_wrap.h:84:78:   required from here/home/iobroker/.node-gyp/10.16.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]                reinterpret_cast<Callback>(callback), type);                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/iobroker/.node-gyp/10.16.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':../node_modules/nan/nan_object_wrap.h:65:61:   required from here/home/iobroker/.node-gyp/10.16.0/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
../src/linux/DeviceINQ.cc:35:14: fatal error: bluetooth/bluetooth.h: Datei oder Verzeichnis nicht gefunden     #include <bluetooth/bluetooth.h>              ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [BluetoothSerialPort.target.mk:105: Release/obj.target/BluetoothSerialPort/src/linux/DeviceINQ.o] Fehler 1
gyp
 ERR! build error gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)gyp ERR! stack     at ChildProcess.emit (events.js:198:13)gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)gyp ERR! System Linux 4.19.58-v7l+gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"gyp ERR! cwd /opt/iobroker/node_modules/node-bluetoothgyp ERR! 
node -v v10.16.0gyp ERR! node-gyp -v v3.8.0gyp ERR! not ok 
Unexpected platform or architecture: linux/armIt seems there is no binary available for your platform/architectureTry to install PhantomJS globally
npm
 ERR! code ELIFECYCLEnpm ERR! errno 1npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`npm ERR! Exit status 1npm ERR! npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2020-03-27T15_12_34_205Z-debug.log
ERROR: host.raspberrypi Cannot install iobroker.phantomjs@1.0.1: 1
ERROR: process exited with code 25

**Comment by Apollon77** [comment]
> Unexpected platform or architecture: linux/armIt seems there is no binary available for your platform/architectureTry to install PhantomJS globally Unexpected platform or architecture: linux/armIt seems there is no binary available for your platform/architectureTry to install PhantomJS globally

Yes, on a raspi you need to install PhantomJS somehow separately first

**Comment by LJSven** [comment]
@Apollon77 Ich habe das gleiche Problem - gibt es irgendwo ein "How-To"? Bin nicht wirklich fit & möchte nicht mein System zerschießen.

**Comment by Apollon77** [comment]
Versucht mal 

```
sudo apt-get update
sudo apt-get install build-essential chrpath libssl-dev libxft-dev
sudo apt-get install libfreetype6 libfreetype6-dev
sudo apt-get install libfontconfig1 libfontconfig1-dev
sudo apt-get install phantomjs
```

Aber keine gewähr ...

**Comment by LJSven** [comment]
Ich bekomme folgende Fehlermedung ->
`root@raspberrypi:/usr/bin# phantomjs --version
QXcbConnection: Could not connect to display 
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
Aborted
`

**Comment by LJSven** [comment]
@Apollon77 Ich konnte jetzt PhantomJS auf meinem Raspberry (ist ein Slave im Multihost-System) intallieren. Es fehlte eine Zeile in der 

`/usr/bin/phantomjs`

Die sieht jetzt bei mir wie folgt aus -> 
```
#!/bin/sh
LD_LIBRARY_PATH="/usr/lib/phantomjs:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH
export QT_QPA_PLATFORM=offscreen
exec "/usr/lib/phantomjs/phantomjs" "$@"
```

Wenn ich den Adapter jetzt installieren möchte wenn ich im Master eingeloggt bin, bleibt die Fehlermeldung. Wenn ich mich auf dem Slave einlogge, schient es zu gehen.

**Comment by LJSven** [comment]
Ich habe jetzt das Problem, daß das Bild zwar im Ordner auf meinem Slave gespeichert wird

```
root@raspberrypi:/opt/iobroker/node_modules/iobroker.phantomjs# ls
admin  bodenfeuchte1.png  bodenfeuchte.png  iob_npm.done  io-package.json  lib	LICENSE  main.js  package.json	README.md
```

Aber wie bekomme ich via Telegram (der auf dem Master) läuft, Zugriff auf das Bild?

**Comment by Apollon77** [comment]
Wenn es so zugegrifen wird per direkten "Filesystem" muss es auf dem gleichen Host laufen

**Comment by Apollon77** [comment]
BTW ... an sich ist das File ja im state ...pixture_png oder so hinterlegt. Das ist ein BinaryState ... kann man also dort auslesen
