### ISSUE TITLE
not working with js-controller 3.x and node 12 ? 

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.phantomjs#15]
Since the update of Node12 and js-controller 3.0.x the Adapter send the error message "take too longe time" 
`

phantomjs.0 | 2020-04-16 17:13:15.970 | debug | (24707) system.adapter.admin.0: logging true
-- | -- | -- | --
phantomjs.0 | 2020-04-16 17:13:09.363 | error | (24707) PhantomJS process required too many time!
phantomjs.0 | 2020-04-16 17:13:09.356 | error | (24707) timeout
phantomjs.0 | 2020-04-16 17:13:09.356 | error | (24707) PhantomJS process does not returned after 7000ms
phantomjs.0 | 2020-04-16 17:13:04.882 | debug | (24707) system.adapter.admin.0: logging false
phantomjs.0 | 2020-04-16 17:13:02.354 | debug | (24707) /opt/iobroker/node_modules/iobroker.phantomjs/lib/rasterize.js  --output "/opt/iobroker/node_modules/iobroker.phantomjs/picture.png"  --width 800 --height 600 --timeout 2000 --clip-top 0 --clip
phantomjs.0 | 2020-04-16 17:13:02.354 | info | (24707) Create 800px*600px in 2000ms -  "http://192.168.178.28/webcam/?action=stream" =>  "/opt/iobroker/node_modules/iobroker.phantomjs/picture.png"

`

**Comment by Apollon77** [comment]
WHat happens if you call the command directly on shell? Dauert es länger als 2s?

**Comment by Apollon77** [comment]
mal "renderTime" state einen höheren Wert gesetzt?
