### ISSUE TITLE
ignore Webserver Port, already 8082 in the object-link

### ISSUE THREAD

**Issue by Ilovegym66** [ioBroker/ioBroker.phantomjs#16]
Hi, the adapter ignore the setup of the webserver, my webserver is at Port 81, the phantomjs adapter set the link in the object phantomjs.0.pictures.picture_png already to http://myiobrokerIP:8082/xxx but I don't have something at 8082.. :-)

If I changed the link to the correct Port, the picture is there. So the Adapter works fine, but the provided Port in the object is wrong.
I found in the main.js a line with the Port in the description, but a change doesn't matter..

**Comment by Apollon77** [comment]
The state that you said is a binary tate ... just the description contains that hard coded portname. I changed the subscription now.

**Comment by Apollon77** [comment]
please test 1.1.0 on GitHub

**Comment by Ilovegym66** [comment]
sorry, same again, description is ok, but the link in the object is faulty - again with 8082.. I dont know, from which thing this 8082 comes.. I have no webservices at 8082.. this port is dead ..

**Comment by Apollon77** [comment]
Please Show a Screenshot

**Comment by Apollon77** [comment]
Maybe it is more an admin topic. To show that with a binary state?

**Comment by Ilovegym66** [comment]
Forum are the Details..

**Comment by Apollon77** [comment]
Please open issue in Admin :-)

https://github.com/ioBroker/ioBroker.admin/blob/master/src/lib/js/selectID.js#L2405
