### ISSUE TITLE
ssl error  - autoconf failed

### ISSUE THREAD

**Issue by liv-in-sky** [ioBroker/ioBroker.phantomjs#19]
I had no errors during the adpter installationm - but if I try use phantom - I get the following error:

`2020-09-24 08:11:12.436  - error: phantomjs.0 (28334) Auto configuration failed
140567742660224:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
140567742660224:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140567742660224:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
140567742660224:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf
`

any hints about that ?

**Comment by Apollon77** [comment]
is libssl_dev installed?

**Comment by liv-in-sky** [comment]
now - yes - I have installed it

the error is now (nearly the same)

`
2020-09-24 09:03:37.360  - error: phantomjs.0 (28334) Auto configuration failed
140671441956480:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
140671441956480:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140671441956480:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
140671441956480:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf


I found this - but have no idea what to do`

**Comment by liv-in-sky** [comment]
I found this :  https://github.com/bazelbuild/rules_closure/issues/351
but have no idea what to do

**Comment by morphygee** [comment]
have the same problem.
the reason for this problem seems to be a nonexistent env variable:
OPENSSL_CONF=/etc/ssl/

I've set it for root an for iobroker user, but after a full reboot only the logged in users see have the set variable. within the running iobroker instance this variable is missing.

do not know how to fix ist :(

**Comment by buanet** [comment]
Ding dong. Any news here?
Looks like phantomjs is not working on Debian Buster because of a missing openssl.conf? 
Tried several workarounds from the linked issues in https://github.com/bazelbuild/rules_closure/issues/351
No success so far.. Any ideas?

Regards,
André

**Comment by drtp** [comment]
Same issue here with ioBroker running in a Docker Container under Debian Buster (node v12.20.0, npm 6.14.8).

**Comment by drtp** [comment]
Okay. I found a possible solution. [See here.](https://forum.iobroker.net/topic/4733/howto-iobroker-unter-docker-auf-synology-diskstation/2308)

Yust add the package libfontconfig AND set the environment "OPENSSL_CONF=/etc/ssl/".

**Comment by liv-in-sky** [comment]
Are there any news about this item - I still can't use phantom with iobroker

**Comment by KoMa1978** [comment]
Same here ...
