### ISSUE TITLE
Installation of 1.1.2 fails

### ISSUE THREAD

**Issue by FRYYYYYY** [ioBroker/ioBroker.phantomjs#20]
Dear all,

the installation of phantomjs version 1.1.2 fails with the following error:

`$ ./iobroker add phantomjs  --host HOSTNAME
NPM version: 6.14.9
npm install iobroker.phantomjs@1.1.2 --loglevel error --prefix "/opt/iobroker" (System call)
Unexpected platform or architecture: linux/armIt seems there is no binary available for your platform/architectureTry to install PhantomJS globally
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`npm ERR! Exit status 1npm ERR! npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2020-11-29T12_48_09_207Z-debug.log
ERROR: host.FrYsmarthome Cannot install iobroker.phantomjs@1.1.2: 1
ERROR: process exited with code 25`

Die debug.log-Datei wirft folgendes aus:

`428 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
429 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
430 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
430 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
430 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
430 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: arm
431 verbose stack Error: phantomjs-prebuilt@2.1.16 install: `node install.js`
431 verbose stack Exit status 1
431 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
431 verbose stack     at EventEmitter.emit (events.js:198:13)
431 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
431 verbose stack     at ChildProcess.emit (events.js:198:13)
431 verbose stack     at maybeClose (internal/child_process.js:982:16)
431 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
432 verbose pkgid phantomjs-prebuilt@2.1.16
433 verbose cwd /opt/iobroker
434 verbose Linux 5.4.72-v7l+
435 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "iobroker.phantomjs@1.1.2" "--loglevel" "error" "--prefix" "/opt/iobroker"
436 verbose node v10.23.0
437 verbose npm  v6.14.9
438 error code ELIFECYCLE
439 error errno 1
440 error phantomjs-prebuilt@2.1.16 install: `node install.js`
440 error Exit status 1
441 error Failed at the phantomjs-prebuilt@2.1.16 install script.
441 error This is probably not a problem with npm. There is likely additional logging output above.
442 verbose exit [ 1, true ]
`

ioBroker.admin 4.1.11
js-controller 3.1.6
npm 6.14.9

libfontconfig
`Note, selecting 'libfontconfig1' instead of 'libfontconfig'`
`libfontconfig1 is already the newest version (2.13.1-2).`

**Comment by Apollon77** [comment]
> Unexpected platform or architecture: linux/armIt seems there is no binary available for your platform/architecture Try to install PhantomJS globally

sorry, but here is all info ... so you need to google and try to get it installed globally on your system
