### ISSUE TITLE
clipHeight" and clipWidth has to be type "string" but received type "number"

### ISSUE THREAD

**Issue by pcjogi** [ioBroker/ioBroker.phantomjs#23]
since js-controller 3.3.5 th following appears in the log

<html>
<body>

phantomjs.0 | 2021-08-09 15:09:14.032 | info | State value to set for "phantomjs.0.clipHeight" has to be type "string" but received type "number"
-- | -- | -- | --
phantomjs.0 | 2021-08-09 15:09:14.029 | info | State value to set for "phantomjs.0.clipWidth" has to be type "string" but received type "number"
phantomjs.0 | 2021-08-09 15:09:13.966 | info | starting. Version 1.1.2 in /opt/iobroker/node_modules/iobroker.phantomjs, node: v12.22.2, js-controller: 3.3.15

</body>
</html>`

**Comment by Apollon77** [comment]
fixed on Github, release soon
