### ISSUE TITLE
Some Datapoints hasn't the correct type

### ISSUE THREAD

**Issue by homecineplexx** [ioBroker/ioBroker.phantomjs#30]
Phantomjs version: 1.1.2

`
phantomjs.0 | 2022-03-14 11:31:15.615 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
phantomjs.0 | 2022-03-14 11:31:15.614 | warn | Object phantomjs.0.scrollLeft is invalid: Default value has to be type "string" but received type "number"
phantomjs.0 | 2022-03-14 11:31:15.506 | warn | This object will not be created in future versions. Please report this to the developer.
phantomjs.0 | 2022-03-14 11:31:15.506 | warn | Object phantomjs.0.scrollTop is invalid: Default value has to be type "string" but received type "number"
phantomjs.0 | 2022-03-14 11:31:15.435 | warn | This object will not be created in future versions. Please report this to the developer.
phantomjs.0 | 2022-03-14 11:31:15.434 | warn | Object phantomjs.0.clipHeight is invalid: Default value has to be type "string" but received type "number"
phantomjs.0 | 2022-03-14 11:31:15.174 | warn | This object will not be created in future versions. Please report this to the developer.
phantomjs.0 | 2022-03-14 11:31:15.173 | warn | Object phantomjs.0.clipWidth is invalid: Default value has to be type "string" but received type "number"
phantomjs.0 | 2022-03-14 11:31:14.875 | warn | This object will not be created in future versions. Please report this to the developer.
phantomjs.0 | 2022-03-14 11:31:14.874 | warn | Object phantomjs.0.clipLeft is invalid: Default value has to be type "string" but received type "number"
phantomjs.0 | 2022-03-14 11:31:14.754 | warn | This object will not be created in future versions. Please report this to the developer.
phantomjs.0 | 2022-03-14 11:31:14.750 | warn | Object phantomjs.0.clipTop is invalid: Default value has to be type "string" but received type "number"

`

**Comment by Apollon77** [comment]
Fixed on Github, release soon
