### ISSUE TITLE
Top und Left Werte im Adapter ändern

### ISSUE THREAD

**Issue by Schatn** [ioBroker/ioBroker.phantomjs#5]
Hallo!

Wäre es möglich, die top und left Werte in der rastersize.js im Adapter selbst zu ändern? Also als weitere Datenpunkte.
page.clipRect = { top: 265, left: 230, width: pageWidth, height: pageHeight };
Damit man von einer Webseite nur einen gewissen Bereich als Screenshot speichert.
Eventuell auch noch die Auflösung:
page.viewportSize = {width: 1920, height: 1080};

Ich hab das momentan nur in der rastersize.js angepasst aber beim nächsten Adapter Update wird das sicher wieder überschrieben.
Danke!!!

**Comment by GermanBluefox** [comment]
Please test from git the actual version

**Comment by Schatn** [comment]
Vielen Dank, funktioniert jetzt wunderbar.
