### ISSUE TITLE
width and size werden ignoriert

### ISSUE THREAD

**Issue by Q7Jensen** [ioBroker/ioBroker.phantomjs#6]
Angegebene width und size werden ignoriert.
Getestet mit folgendem script:

    sendTo('phantomjs.0', 'send', {
        url: 'http://google.com',
        output: 'image.png',
        width: 300,
        height: 200,
       renderTime: 10000,
       online: true
    }, function (result) {
        console.log(result.error + ' ' + result.output);
    });

![phantom](https://user-images.githubusercontent.com/5997996/38766143-1950acf6-3fce-11e8-864c-a2abd164aa17.JPG)

Adapter Version : 1.0.0
OS : debian

in rasterrize.js
das funktioniert nicht
        page.viewportSize.width = parseInt(system.args[a], 10);
        page.viewportSize.height = parseInt(system.args[a], 10);

wie früher, das geht
        page.viewportSize = { width: pageWidth, height: pageHeight };

**Comment by dwm66** [comment]
same issue here ...

**Comment by oliveramann** [comment]
Same Problem
Adapter Version: 1.0
Plattform: linux (LXC-Ubuntu)
RAM: 7.6 GB
Node.js: v6.13.1
NPM: 5.7.1

**Comment by dwm66** [comment]
Looks ok now, tested w/ several resolutions, works as expected!
1000x TNX
